// Generated by gencpp from file actuator/actuator_data.msg
// DO NOT EDIT!


#ifndef ACTUATOR_MESSAGE_ACTUATOR_DATA_H
#define ACTUATOR_MESSAGE_ACTUATOR_DATA_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace actuator
{
template <class ContainerAllocator>
struct actuator_data_
{
  typedef actuator_data_<ContainerAllocator> Type;

  actuator_data_()
    : height_offset(0)  {
    }
  actuator_data_(const ContainerAllocator& _alloc)
    : height_offset(0)  {
    }



   typedef int32_t _height_offset_type;
  _height_offset_type height_offset;




  typedef boost::shared_ptr< ::actuator::actuator_data_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::actuator::actuator_data_<ContainerAllocator> const> ConstPtr;

}; // struct actuator_data_

typedef ::actuator::actuator_data_<std::allocator<void> > actuator_data;

typedef boost::shared_ptr< ::actuator::actuator_data > actuator_dataPtr;
typedef boost::shared_ptr< ::actuator::actuator_data const> actuator_dataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::actuator::actuator_data_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::actuator::actuator_data_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace actuator

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'actuator': ['/home/saruman/workspaces/ros_workspace/case_robotics/nasa/catkin_wkspace/src/actuator/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::actuator::actuator_data_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::actuator::actuator_data_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::actuator::actuator_data_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::actuator::actuator_data_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::actuator::actuator_data_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::actuator::actuator_data_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::actuator::actuator_data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "42b409eee8002bc6b9d50cfde1aaf409";
  }

  static const char* value(const ::actuator::actuator_data_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x42b409eee8002bc6ULL;
  static const uint64_t static_value2 = 0xb9d50cfde1aaf409ULL;
};

template<class ContainerAllocator>
struct DataType< ::actuator::actuator_data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "actuator/actuator_data";
  }

  static const char* value(const ::actuator::actuator_data_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::actuator::actuator_data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 height_offset\n\
";
  }

  static const char* value(const ::actuator::actuator_data_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::actuator::actuator_data_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.height_offset);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct actuator_data_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::actuator::actuator_data_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::actuator::actuator_data_<ContainerAllocator>& v)
  {
    s << indent << "height_offset: ";
    Printer<int32_t>::stream(s, indent + "  ", v.height_offset);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ACTUATOR_MESSAGE_ACTUATOR_DATA_H
