// Generated by gencpp from file ex/ex_msg.msg
// DO NOT EDIT!


#ifndef EX_MESSAGE_EX_MSG_H
#define EX_MESSAGE_EX_MSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace ex
{
template <class ContainerAllocator>
struct ex_msg_
{
  typedef ex_msg_<ContainerAllocator> Type;

  ex_msg_()
    : header()
    , msg()
    , first(0)
    , second(0)  {
    }
  ex_msg_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , msg(_alloc)
    , first(0)
    , second(0)  {
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _msg_type;
  _msg_type msg;

   typedef int32_t _first_type;
  _first_type first;

   typedef int32_t _second_type;
  _second_type second;




  typedef boost::shared_ptr< ::ex::ex_msg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ex::ex_msg_<ContainerAllocator> const> ConstPtr;

}; // struct ex_msg_

typedef ::ex::ex_msg_<std::allocator<void> > ex_msg;

typedef boost::shared_ptr< ::ex::ex_msg > ex_msgPtr;
typedef boost::shared_ptr< ::ex::ex_msg const> ex_msgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ex::ex_msg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ex::ex_msg_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ex

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'ex': ['/home/saruman/workspaces/ros_workspace/case_robotics/nasa/catkin_wkspace/src/ex/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ex::ex_msg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ex::ex_msg_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ex::ex_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ex::ex_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ex::ex_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ex::ex_msg_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ex::ex_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "de40b4cf0841e7ee17696b7506c4c036";
  }

  static const char* value(const ::ex::ex_msg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xde40b4cf0841e7eeULL;
  static const uint64_t static_value2 = 0x17696b7506c4c036ULL;
};

template<class ContainerAllocator>
struct DataType< ::ex::ex_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ex/ex_msg";
  }

  static const char* value(const ::ex::ex_msg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ex::ex_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
string msg\n\
int32 first\n\
int32 second\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::ex::ex_msg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ex::ex_msg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.msg);
      stream.next(m.first);
      stream.next(m.second);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct ex_msg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ex::ex_msg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ex::ex_msg_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "msg: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.msg);
    s << indent << "first: ";
    Printer<int32_t>::stream(s, indent + "  ", v.first);
    s << indent << "second: ";
    Printer<int32_t>::stream(s, indent + "  ", v.second);
  }
};

} // namespace message_operations
} // namespace ros

#endif // EX_MESSAGE_EX_MSG_H
