// Generated by gencpp from file ex/ex_srv.msg
// DO NOT EDIT!


#ifndef EX_MESSAGE_EX_SRV_H
#define EX_MESSAGE_EX_SRV_H

#include <ros/service_traits.h>


#include <ex/ex_srvRequest.h>
#include <ex/ex_srvResponse.h>


namespace ex
{

struct ex_srv
{

typedef ex_srvRequest Request;
typedef ex_srvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ex_srv
} // namespace ex


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ex::ex_srv > {
  static const char* value()
  {
    return "85a734c776d49ce7e013b15b395d3f69";
  }

  static const char* value(const ::ex::ex_srv&) { return value(); }
};

template<>
struct DataType< ::ex::ex_srv > {
  static const char* value()
  {
    return "ex/ex_srv";
  }

  static const char* value(const ::ex::ex_srv&) { return value(); }
};


// service_traits::MD5Sum< ::ex::ex_srvRequest> should match 
// service_traits::MD5Sum< ::ex::ex_srv > 
template<>
struct MD5Sum< ::ex::ex_srvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ex::ex_srv >::value();
  }
  static const char* value(const ::ex::ex_srvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ex::ex_srvRequest> should match 
// service_traits::DataType< ::ex::ex_srv > 
template<>
struct DataType< ::ex::ex_srvRequest>
{
  static const char* value()
  {
    return DataType< ::ex::ex_srv >::value();
  }
  static const char* value(const ::ex::ex_srvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ex::ex_srvResponse> should match 
// service_traits::MD5Sum< ::ex::ex_srv > 
template<>
struct MD5Sum< ::ex::ex_srvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ex::ex_srv >::value();
  }
  static const char* value(const ::ex::ex_srvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ex::ex_srvResponse> should match 
// service_traits::DataType< ::ex::ex_srv > 
template<>
struct DataType< ::ex::ex_srvResponse>
{
  static const char* value()
  {
    return DataType< ::ex::ex_srv >::value();
  }
  static const char* value(const ::ex::ex_srvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // EX_MESSAGE_EX_SRV_H
